name: Deploy to Render

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Call Render Deploy Webhook
        run: |
          curl -X GET "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ https://api.render.com/deploy/srv-cvv177hr0fns73a0hamg?key=91aLCf1eMkM }}
