name: CI Pipeline

on:
  push:
    branches:
      - main
      - development
      - features/*
  pull_request:

jobs:
  check:
    name: Lint, Build, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build SASS
        run: npm run sass:build

      - name: Lint 
        run: npm run lint

      - name: Prettier 
        run: npm run prettier:check

      - name: TS build
        run: npm run tsc:build

      - name: Run tests
        run: npm run test
